version: "3.7"
services:
  app:
    build:
      args:
        user: cristian
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ponto_eletronico
    container_name: ponto_eletronico-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ponto_eletronico

  nginx:
    image: nginx:alpine
    container_name: ponto_eletronico-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - ponto_eletronico

networks:
  ponto_eletronico:
    driver: bridge
